---
- name: install supervisor
  apt: name=supervisor state=latest

- name: fallback maprotate
  template: src=maps.cfg dest=/mnt/openarena/.openarena/baseoa/maps.cfg
  notify: restart openarena

- name: openarena server config
  template: src=server.cfg dest=/mnt/openarena/.openarena/baseoa/server.cfg
  notify: restart openarena

- name: openarena supervisor config
  template: src=openarena.conf dest=/etc/supervisor/conf.d/openarena.conf
  notify: restart openarena

- name: maps
  get_url: url={{item.0.url}}/{{item.1.name}}.pk3 dest=/mnt/openarena/baseoa/{{item.1.mapname|default(item.1.name)}}.pk3 force={{item.1.force|default(false)}}
  notify: restart openarena
  with_subelements:
    - map_sources
    - maps
  tags:
    - maps
