#!/usr/bin/env ansible-playbook -i hosts --ask-sudo-pass --timeout=30

---
- name: Openarena
  hosts:
    - linode
  user: root
  remote_user: johanadm
  sudo: yes
  vars_files:
    - secret_vars.yaml

  roles:
    - { role: munerator, tags: ['munerator'], modules: ['old'] }
    - { role: openarena, tags: ['openarena'] }
    - { role: nginx, tags: ['nginx'] }
