#!/usr/bin/env ansible-playbook -i hosts --ask-sudo-pass --ask-vault-pass --skip-tag maps

---
- name: Openarena
  hosts: brensen
  user: root
  remote_user: johanadm
  sudo: yes
  vars_files:
    - vars.yaml

  roles:
    - { role: munerator, tags: ['munerator'] }
    - openarena
