---
- name: install supervisor
  apt: name=supervisor state=latest

- name: install munerator
  pip: name=munerator state=latest
  notify: restart munerator

- name: munerator supervisor config
  template: src=munerator.conf dest=/etc/supervisor/conf.d/munerator.conf
  notify: restart munerator

