---
- apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen'
- apt_key: id=7F0CEB10 state=present url=http://docs.mongodb.org/10gen-gpg-key.asc

- name: install supervisor
  apt: name=supervisor state=latest

- pip: name=pip state=latest virtualenv=/opt/munerator

- name: install munerator
  pip: name='munerator[db]' state=latest virtualenv=/opt/munerator extra_args=--process-dependency-links
  notify: restart munerator

- name: munerator supervisor config
  template: src=munerator.conf dest=/etc/supervisor/conf.d/munerator.conf
  notify: restart munerator

- cron: name="periodic tasks" minute=0 hour="14,18,0" job="/opt/munerator/bin/munerator periodic" user=openarena

- name: install mongodb
  apt: name=mongodb-org state=latest

- name: mongo config
  lineinfile: dest=/etc/mongodb.conf regexp=^dbpath= line=dbpath={{oa_base}}/munerator_db/
  notify: restart mongodb

- name: mongo config
  lineinfile: dest=/etc/mongodb.conf line=smallfiles=true
  notify: restart mongodb

- name: mongo database
  file: dest={{oa_base}}/munerator_db state=directory owner=mongodb group=mongodb
  notify: restart mongodb