---
- name: install supervisor
  apt: name=supervisor state=latest

- name: install munerator
  pip: name='munerator[restapi,store]' state=latest
  notify: restart munerator

- name: munerator supervisor config
  template: src=munerator.conf dest=/etc/supervisor/conf.d/munerator.conf
  notify: restart munerator

- cron: name="find assets" minute=0 hour="14,18,0" job="nice munerator assets" user=openarena

- name: install mongodb
  apt: name=mongodb state=latest

- name: mongo config
  lineinfile: dest=/etc/mongodb.conf regexp=^dbpath= line=dbpath={{oa_base}}/munerator_db/
  notify: restart mongodb

- name: mongo database
  file: dest={{oa_base}}/munerator_db state=directory owner=mongodb group=mongodb
  notify: restart mongodb
