---
- name: reread supervisor
  command: supervisorctl reread

- name: restart munerator
  supervisorctl: name='munerator:' state=restarted

- name: restart mongodb
  service: name=mongod state=restarted
